### DISCUSSION TITLE
Is it possible to use up xpkg with a remote Artifactory registry ?

### DISCUSSION THREAD

**Discussion by vmahe35** [upbound/vscode-up#24] [General]
I am trying to get Crossplane packages with the `up` CLI from a remote Artifactory registry that I managed to build and push using kubectl crossplane plugin.

Can you give instructions on how to do that ?

I would like to do something like : `up xpkg dep <my-server>/<registry-path>/my-provider:0.0.2` but it doesn't work.

Because I have an issue in VSCode whenever I want to reference such an external provider into my `crossplane.yaml` file : 
```yaml
spec:
  crossplane:
    version: ">=v1.12.0"
  dependsOn:
  - provider: <my-server>/<registry-path>/my-provider
    version: ">=v0.0.2"
```
and in the VSCode editor, an error message like this appears when I mouse over the underlined text :
> Package <my-server>/<registry-path>/my-provider does not exist locally. Please run `up xpkg dep` to fix.

I have installed up v0.19.1 and VSCode upbound plugin v0.0.5.
